### ISSUE TITLE
not honoring nested includes inside include that uses leveloffset

### ISSUE THREAD

**Issue by liljenstolpe** [asciidoctor/asciidoctor-reducer#45]
I am trying to use this to build a single README out of a collection of docs in a subfolder.  There are nested includes, however, only the initial (top level) includes are being actually proceed.  includes in the those included files are being missed.  An example

README.adoc has a line
include::docs/workflows.adoc[leveloffset=+1]

workflows.adoc has a line
include::scripts.adoc[leveloffset=+1]  // scripts is also in docs

scripts.adoc has a line
include::rmdvc.adoc[leveloffset=+1] // rmdvc alsi is in the docs dir

The result in the rendered README-OUT.adoc is
```
:leveloffset: +1

# Workflows

include::scripts.adoc[leveloffset=+1]

:leveloffset!:
```

You can see that it didn't process the scripts.adoc include (therefore, none of the others).

No errors get thrown. 

I thought it might be a path problem, but when I change all of the include paths to include 'docs' as the parent dir, it does throw an error about not being able to find '/home/<user>/repo/docs/scripts.adoc'

What am I missing?

**Comment by mojavelinux** [comment]
I just (re)discovered this issue this past week and came here to file this issue. It seems like if an include uses leveloffset, then includes inside that include don't get replaced properly. And, lo and behold, we are missing a test for it.

The reason this happens is because the reader injects `leveloffset` attribute entries into the included file, but the replacer is not accounting for these lines. Therefore, it can't find the include directive to replace.

In the meantime, the workaround is to move `leveloffset` to around the include directive.

```
:leveloffset: +1

include::scripts.adoc[]

:!leveloffset:
```

I'll go ahead and add a test and fix this issue for the next release.

**Comment by mojavelinux** [comment]
The fix for this issue is now available in the latest release.
