### ISSUE TITLE
How to use the attributes

### ISSUE THREAD

**Issue by HCGruler** [asciidoctor/asciidoctor-reducer#51]
I want to have the Readme.adoc in the root of the repo - Includes will be made from individual chapters with their own adoc. 

Now there is the problem with the images - during development would be nice to have the images in one folder - but then the chapter adoc would have different path. Here the idea was to change the imagesdir attribute when reducing the file. 
Until now this is not working.

**Comment by mojavelinux** [comment]
If you need help using an Asciidoctor library, please ask your question in the project chat at https://chat.asciidoctor.org.

I can assure you that Asciidoctor Reducer is designed exactly the way it is supposed to work. It brings the contents of all include files into the current document, but otherwise leaves the attribute entries (such as imagesdir) alone. There is no reason why they should stop working. If you can prove otherwise, please provide a failing test case to demonstrate the problem. Otherwise, there is no clear action to take.
